car:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    left_steering_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_steering
      pid: {p: 1.0, i: 1.0, d: 0.0}

    right_steering_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_steering
      pid: {p: 1.0, i: 1.0, d: 0.0}

    left_drive_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_rear_wheel_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}

    right_drive_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_rear_wheel_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}

    front_left_drive_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_front_wheel_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}

    front_right_drive_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_front_wheel_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}