/* Generated by Cython 0.29.14 */

#ifndef __PYX_HAVE__py_driver
#define __PYX_HAVE__py_driver

#include "Python.h"

#ifndef __PYX_HAVE_API__py_driver

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *instantiatePyCarRobot(void);
__PYX_EXTERN_C bool set_throttle(PyObject *, float);
__PYX_EXTERN_C bool set_angle(PyObject *, float);

#endif /* !__PYX_HAVE_API__py_driver */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpy_driver(void);
#else
PyMODINIT_FUNC PyInit_py_driver(void);
#endif

#endif /* !__PYX_HAVE__py_driver */
