<?xml version="1.0"?>
<!--
  Robot model adapted from https://github.com/CIR-KIT/steer_drive_ros/blob/kinetic-devel/steer_drive_controller/test/common/urdf/steerbot.xacro
  Modifications:
    Remove base_footprint link. Useful for navigation but not necessary for a simple example.
    Added materials for URDF
    Updated inertials
  Geometry:
    The Ackermann steering controllers require the longitudinal
    separation between the front and back wheel axes and the
    lateral separation between the left and right front steering axes.
    
    For this model:
    wheel_separation_h = 2 * axle_offset = 0.28
    wheel_separation_w = car_width - 2 * 0.5 * wheel_thickness = 0.155
-->
<robot name="car" xmlns:xacro="http://wiki.ros.org/xacro">
  <!-- Include xacro for inertials, materials and wheels -->
  <xacro:include filename="$(find robot_description)/urdf/wheel.xacro"/>
  <xacro:include filename="$(find robot_description)/urdf/car_gazebo.xacro" />

  <xacro:property name="robot_namespace" value="/car"/>


  <!-- Math constants -->
  <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>

  <!-- Robot dimensions -->
  <xacro:property name="car_length" value="0.4" /> 
  <xacro:property name="car_width" value="0.18" /> 
  <xacro:property name="car_height" value="0.18" /> 
  <xacro:property name="car_mass" value="2" /> 

  <!-- Wheel link dimensions -->
  <xacro:property name="wheel_radius" value="0.0325" />
  <xacro:property name="wheel_thickness" value="0.025" />
  <xacro:property name="wheel_mass" value="0.00355" />

  <!-- Steering link dimensions -->
  <xacro:property name="steer_radius" value="0.02" />
  <xacro:property name="steer_thickness" value="0.004" />
  <xacro:property name="steer_mass" value="0.0008" />

  <!-- Axle positions -->
  <xacro:property name="axle_offset" value="0.14" />
  <xacro:property name="steer_offset" value="0.02" />

  <xacro:macro name="dummy_visual">
    <visual>
      <geometry>
        <box size =".001 .001 .001"/>
      </geometry>
      <xacro:default_origin />
    </visual>
  </xacro:macro>

  <xacro:macro name="default_origin">
       <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:macro>

  <!-- Base link -->
  <link name="base_link">
    <collision>
        <xacro:default_origin />
        <geometry>
            <box size="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <xacro:dummy_visual />
  </link>

  <link name="body">
    <inertial>
      <origin xyz="0.7 0 0.043" rpy="0 0 0"/> 
      <mass value="${car_mass}" />
      <inertia ixx="0.0332083" ixy="0.0" ixz="0.0" iyy="0.01302083" iyz="0.0" izz="0.03685416"/>
    </inertial>

    <collision>
        <!-- <origin rpy="0 0 0" xyz="0.14 0 0.063"/> -->
        <xacro:default_origin />
        <geometry>
            <box size="${car_length} ${car_width} ${car_height}"/>
        </geometry>
    </collision>

    <visual>
      <geometry>
        <!--Dimensions: 37x20xheight   height may very depending on components, should be ~20cm-->
        <mesh filename="package://robot_description/models/car_robot/meshes/car.dae"/>
      </geometry>
      <!-- <origin rpy="0 0 0" xyz="0.147 0 0.063"/> TODO -->
      <xacro:default_origin />
    </visual>
  </link>

  <joint name="base_link_to_body" type="fixed">
    <parent link="base_link"/>
    <child link="body"/>
    <origin xyz="0 0 ${wheel_radius}"/>
    <axis   xyz="0 1 0"/>
  </joint>

  <!-- Front steer and rear wheel joints required for ackermann_steering_controller -->
  <xacro:front_steer
    name="front"
    parent="base"
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}" 
    steer_mass="${steer_mass}"
    axle_offset="${axle_offset}"
    steer_height="${wheel_radius+steer_offset}">
  </xacro:front_steer>

  <!-- Steerable front side wheels -->
  <xacro:front_wheel_lr 
    name="front_right"
    parent="base"
    reflect="-1"
    wheel_radius="${wheel_radius}"
    wheel_thickness="${wheel_thickness}" 
    wheel_mass="${wheel_mass}" 
    wheel_is_right="1"
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}" 
    steer_mass="${steer_mass}" 
    car_length="${car_length}"
    car_width="${car_width}"
    axle_offset="${axle_offset}"
    steer_height="${wheel_radius+steer_offset}">
  </xacro:front_wheel_lr>
  <xacro:front_wheel_lr
    name="front_left"
    parent="base"
    reflect="1"
    wheel_radius="${wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}" 
    wheel_is_right="0" 
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}" 
    steer_mass="${steer_mass}" 
    car_length="${car_length}"
    car_width="${car_width}"
    axle_offset="${axle_offset}"
    steer_height="${wheel_radius+steer_offset}">
  </xacro:front_wheel_lr>

  <!-- Rear side wheels -->
  <xacro:rear_wheel_lr
    name="rear_right"
    parent="base"
    wheel_radius="${wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}"
    wheel_is_right="1">
    <origin xyz="${-axle_offset} ${-car_width/2+wheel_thickness/2} 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel_lr>
  <xacro:rear_wheel_lr
    name="rear_left"
    parent="base"
    wheel_radius="${wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}"
    wheel_is_right="0">
    <origin xyz="${-axle_offset} ${+car_width/2-wheel_thickness/2} 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel_lr>

  <!-- rear drive wheel -->
  <xacro:rear_wheel
    name="rear"
    parent="base"
    wheel_radius="${wheel_radius/4}"
    wheel_thickness="${wheel_thickness/2}"
    wheel_mass="${wheel_mass/32}">
    <origin xyz="${-axle_offset} 0 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel>

  <!-- Colour -->
  <gazebo reference="base_link">
    <material>Gazebo/Green</material>
  </gazebo>

</robot>